// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/xdu31/exercise-service/pkg/server/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetExercisesForMuscleReq struct {
	MuscleName           string   `protobuf:"bytes,1,opt,name=muscle_name,json=muscleName,proto3" json:"muscle_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExercisesForMuscleReq) Reset()         { *m = GetExercisesForMuscleReq{} }
func (m *GetExercisesForMuscleReq) String() string { return proto.CompactTextString(m) }
func (*GetExercisesForMuscleReq) ProtoMessage()    {}
func (*GetExercisesForMuscleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de1c4de0785b0888, []int{0}
}

func (m *GetExercisesForMuscleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExercisesForMuscleReq.Unmarshal(m, b)
}
func (m *GetExercisesForMuscleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExercisesForMuscleReq.Marshal(b, m, deterministic)
}
func (m *GetExercisesForMuscleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExercisesForMuscleReq.Merge(m, src)
}
func (m *GetExercisesForMuscleReq) XXX_Size() int {
	return xxx_messageInfo_GetExercisesForMuscleReq.Size(m)
}
func (m *GetExercisesForMuscleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExercisesForMuscleReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExercisesForMuscleReq proto.InternalMessageInfo

func (m *GetExercisesForMuscleReq) GetMuscleName() string {
	if m != nil {
		return m.MuscleName
	}
	return ""
}

type GetExercisesForMuscleResp struct {
	Results              []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExercisesForMuscleResp) Reset()         { *m = GetExercisesForMuscleResp{} }
func (m *GetExercisesForMuscleResp) String() string { return proto.CompactTextString(m) }
func (*GetExercisesForMuscleResp) ProtoMessage()    {}
func (*GetExercisesForMuscleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de1c4de0785b0888, []int{1}
}

func (m *GetExercisesForMuscleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExercisesForMuscleResp.Unmarshal(m, b)
}
func (m *GetExercisesForMuscleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExercisesForMuscleResp.Marshal(b, m, deterministic)
}
func (m *GetExercisesForMuscleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExercisesForMuscleResp.Merge(m, src)
}
func (m *GetExercisesForMuscleResp) XXX_Size() int {
	return xxx_messageInfo_GetExercisesForMuscleResp.Size(m)
}
func (m *GetExercisesForMuscleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExercisesForMuscleResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetExercisesForMuscleResp proto.InternalMessageInfo

func (m *GetExercisesForMuscleResp) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type GetMusclesForExerciseReq struct {
	ExerciseName         string   `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMusclesForExerciseReq) Reset()         { *m = GetMusclesForExerciseReq{} }
func (m *GetMusclesForExerciseReq) String() string { return proto.CompactTextString(m) }
func (*GetMusclesForExerciseReq) ProtoMessage()    {}
func (*GetMusclesForExerciseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de1c4de0785b0888, []int{2}
}

func (m *GetMusclesForExerciseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMusclesForExerciseReq.Unmarshal(m, b)
}
func (m *GetMusclesForExerciseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMusclesForExerciseReq.Marshal(b, m, deterministic)
}
func (m *GetMusclesForExerciseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMusclesForExerciseReq.Merge(m, src)
}
func (m *GetMusclesForExerciseReq) XXX_Size() int {
	return xxx_messageInfo_GetMusclesForExerciseReq.Size(m)
}
func (m *GetMusclesForExerciseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMusclesForExerciseReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMusclesForExerciseReq proto.InternalMessageInfo

func (m *GetMusclesForExerciseReq) GetExerciseName() string {
	if m != nil {
		return m.ExerciseName
	}
	return ""
}

type GetMusclesForExerciseResp struct {
	Results              []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMusclesForExerciseResp) Reset()         { *m = GetMusclesForExerciseResp{} }
func (m *GetMusclesForExerciseResp) String() string { return proto.CompactTextString(m) }
func (*GetMusclesForExerciseResp) ProtoMessage()    {}
func (*GetMusclesForExerciseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de1c4de0785b0888, []int{3}
}

func (m *GetMusclesForExerciseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMusclesForExerciseResp.Unmarshal(m, b)
}
func (m *GetMusclesForExerciseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMusclesForExerciseResp.Marshal(b, m, deterministic)
}
func (m *GetMusclesForExerciseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMusclesForExerciseResp.Merge(m, src)
}
func (m *GetMusclesForExerciseResp) XXX_Size() int {
	return xxx_messageInfo_GetMusclesForExerciseResp.Size(m)
}
func (m *GetMusclesForExerciseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMusclesForExerciseResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMusclesForExerciseResp proto.InternalMessageInfo

func (m *GetMusclesForExerciseResp) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*GetExercisesForMuscleReq)(nil), "service.GetExercisesForMuscleReq")
	proto.RegisterType((*GetExercisesForMuscleResp)(nil), "service.GetExercisesForMuscleResp")
	proto.RegisterType((*GetMusclesForExerciseReq)(nil), "service.GetMusclesForExerciseReq")
	proto.RegisterType((*GetMusclesForExerciseResp)(nil), "service.GetMusclesForExerciseResp")
}

func init() {
	proto.RegisterFile("github.com/xdu31/exercise-service/pkg/server/pb/service.proto", fileDescriptor_de1c4de0785b0888)
}

var fileDescriptor_de1c4de0785b0888 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xaf, 0x48, 0x29, 0x35, 0x36, 0xd4, 0x4f, 0xad, 0x48,
	0x2d, 0x4a, 0xce, 0x2c, 0x4e, 0xd5, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0xc8,
	0x4e, 0xd7, 0x07, 0xb1, 0x53, 0x8b, 0xf4, 0x0b, 0x92, 0xf4, 0xa1, 0xa2, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0xec, 0x50, 0xae, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62,
	0x41, 0xa6, 0x7e, 0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x99,
	0x94, 0x0e, 0x98, 0x4a, 0xd6, 0x4d, 0x4f, 0xcd, 0xd3, 0x2d, 0x2e, 0x4f, 0x4c, 0x4f, 0x4f, 0x2d,
	0xd2, 0xcf, 0x2f, 0x00, 0xab, 0xc0, 0x54, 0xad, 0x64, 0xcd, 0x25, 0xe1, 0x9e, 0x5a, 0xe2, 0x0a,
	0x75, 0x47, 0xb1, 0x5b, 0x7e, 0x91, 0x6f, 0x69, 0x71, 0x72, 0x4e, 0x6a, 0x50, 0x6a, 0xa1, 0x90,
	0x3c, 0x17, 0x77, 0x2e, 0x98, 0x13, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0xc4, 0x05, 0x11, 0xf2, 0x4b, 0xcc, 0x4d, 0x55, 0x32, 0xe5, 0x92, 0xc4, 0xa1, 0xb9, 0xb8,
	0x40, 0x48, 0x82, 0x8b, 0xbd, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0xa4, 0x58, 0x82, 0x51, 0x81, 0x59,
	0x83, 0x33, 0x08, 0xc6, 0x55, 0xb2, 0x07, 0xdb, 0x09, 0x51, 0x0a, 0xd2, 0x04, 0x33, 0x00, 0x64,
	0xa7, 0x32, 0x17, 0x2f, 0x2c, 0x50, 0x90, 0x6d, 0xe5, 0x81, 0x09, 0x22, 0xd9, 0x8b, 0xcd, 0x00,
	0x7c, 0xf6, 0x1a, 0x9d, 0x64, 0xe2, 0xe2, 0x87, 0x99, 0x13, 0x0c, 0x09, 0x4b, 0xa1, 0x19, 0x8c,
	0x5c, 0xa2, 0x58, 0xfd, 0x20, 0xa4, 0xa8, 0x07, 0x0b, 0x7e, 0x5c, 0x01, 0x24, 0xa5, 0x44, 0x48,
	0x49, 0x71, 0x81, 0x92, 0xc5, 0x24, 0x47, 0x2e, 0x2e, 0x8e, 0x92, 0xa2, 0xc4, 0xcc, 0xbc, 0xcc,
	0xbc, 0xf4, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xa9, 0x0a, 0x29, 0xc3, 0x63, 0xbe, 0x38, 0x3e, 0x2d,
	0xbf, 0x28, 0x1e, 0x12, 0xa6, 0xfa, 0xd5, 0x48, 0xc1, 0x5d, 0x2b, 0x34, 0x0b, 0xe2, 0x34, 0x4c,
	0x6f, 0xa2, 0x3a, 0x0d, 0x6b, 0x38, 0xa2, 0x3a, 0x0d, 0x7b, 0x48, 0x29, 0x59, 0x61, 0x3a, 0x4d,
	0x5d, 0x48, 0x55, 0x1f, 0xe2, 0x08, 0x88, 0xc3, 0x60, 0xce, 0xd4, 0xaf, 0x46, 0x89, 0x95, 0x5a,
	0x27, 0xd3, 0x28, 0x63, 0x52, 0x53, 0xb3, 0x75, 0x41, 0x52, 0x12, 0x1b, 0x38, 0xd5, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xf7, 0x1e, 0x1c, 0x0b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExerciseServiceClient is the client API for ExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExerciseServiceClient interface {
	GetExercisesForMuscle(ctx context.Context, in *GetExercisesForMuscleReq, opts ...grpc.CallOption) (*GetExercisesForMuscleResp, error)
	GetMusclesForExercise(ctx context.Context, in *GetMusclesForExerciseReq, opts ...grpc.CallOption) (*GetMusclesForExerciseResp, error)
}

type exerciseServiceClient struct {
	cc *grpc.ClientConn
}

func NewExerciseServiceClient(cc *grpc.ClientConn) ExerciseServiceClient {
	return &exerciseServiceClient{cc}
}

func (c *exerciseServiceClient) GetExercisesForMuscle(ctx context.Context, in *GetExercisesForMuscleReq, opts ...grpc.CallOption) (*GetExercisesForMuscleResp, error) {
	out := new(GetExercisesForMuscleResp)
	err := c.cc.Invoke(ctx, "/service.exerciseService/GetExercisesForMuscle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetMusclesForExercise(ctx context.Context, in *GetMusclesForExerciseReq, opts ...grpc.CallOption) (*GetMusclesForExerciseResp, error) {
	out := new(GetMusclesForExerciseResp)
	err := c.cc.Invoke(ctx, "/service.exerciseService/GetMusclesForExercise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseServiceServer is the server API for ExerciseService service.
type ExerciseServiceServer interface {
	GetExercisesForMuscle(context.Context, *GetExercisesForMuscleReq) (*GetExercisesForMuscleResp, error)
	GetMusclesForExercise(context.Context, *GetMusclesForExerciseReq) (*GetMusclesForExerciseResp, error)
}

func RegisterExerciseServiceServer(s *grpc.Server, srv ExerciseServiceServer) {
	s.RegisterService(&_ExerciseService_serviceDesc, srv)
}

func _ExerciseService_GetExercisesForMuscle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExercisesForMuscleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExercisesForMuscle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.exerciseService/GetExercisesForMuscle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExercisesForMuscle(ctx, req.(*GetExercisesForMuscleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetMusclesForExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMusclesForExerciseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetMusclesForExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.exerciseService/GetMusclesForExercise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetMusclesForExercise(ctx, req.(*GetMusclesForExerciseReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExerciseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.exerciseService",
	HandlerType: (*ExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExercisesForMuscle",
			Handler:    _ExerciseService_GetExercisesForMuscle_Handler,
		},
		{
			MethodName: "GetMusclesForExercise",
			Handler:    _ExerciseService_GetMusclesForExercise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/xdu31/exercise-service/pkg/server/pb/service.proto",
}
