// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/xdu31/exercise-service/pkg/server/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/xdu31/exercise-service/pkg/server/pb/service.proto

It has these top-level messages:
	GetExercisesForMuscleReq
	GetExercisesForMuscleResp
	GetMusclesForExerciseReq
	GetMusclesForExerciseResp
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *GetExercisesForMuscleReq) Preprocess() error {

	return nil
}

func (m *GetExercisesForMuscleResp) Preprocess() error {

	return nil
}

func (m *GetMusclesForExerciseReq) Preprocess() error {

	return nil
}

func (m *GetMusclesForExerciseResp) Preprocess() error {

	return nil
}
